version: '2.3'
services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_DB=ambari
      - POSTGRES_PASSWORD=ambari
      - POSTGRES_USER=ambari
  ambari-server:
    image: webcenter/ambari-server:latest
    links:
      - postgres:db
    hostname: ambari-server
  ambari-agent:
    image: webcenter/ambari-agent:latest
    links:
      - ambari-server:ambari-server
    hostname: ambari-agent
  test:
    image: golang:1.9
    working_dir: /go/src/github.com/disaster37/go-ambari-rest
    volumes:
      - .:/go/src/github.com/disaster37/go-ambari-rest
    command: "bash -c \"go get -t ./... && go test ./...\""
    links:
      - ambari-server:ambari-server
  build:
    image: golang:1.9
    working_dir: /go/src/github.com/disaster37/go-ambari-rest
    volumes:
      - .:/go/src/github.com/disaster37/go-ambari-rest
    command: "bash -c \"go get -d ./... && go get github.com/mitchellh/gox && gox -output 'release/ambari-cli_{{.OS}}_{{.Arch}}'\""
  curl:
    image: appropriate/curl
    links:
      - ambari-server:ambari-server
  cli:
    image: debian
    volumes:
      - .:/workspace
    working_dir: /workspace
    entrypoint: "/workspace/release/ambari-cli_linux_amd64"
    links:
      - ambari-server:ambari-server